spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
