server:
  port: 8086

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ticketmanager255@gmail.com
    password: cfjh dimw gmnc dlht
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    name: customer
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


rabbitmq:
  exchanges:
    internal: internal.exchange
  email-queue:
    email: email.queue
  email-routing-keys:
    internal-email: internal.email.routing-key


email:
    sender:
      strategy: simpleMailService #simpleMailService #fakeEmailService


openapi:
  info:
    title: Noti Doc
    version: 1.0.0
  service:
    description: Noti APIs
    url: http://localhost:8086
